stages:
  - test

test:
  stage: test
  image: python:3.11-bookworm
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  before_script:
    - python -V
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install poetry
    - poetry install
    - poetry -C cfmtoolbox install
    - poetry -C cfmtoolbox-random-sampling install
    - poetry -C cfmtoolbox-uvl-import install
    - poetry -C cfmtoolbox-uvl-export install
  script:
    - poetry run ruff check .
    - poetry run ruff format --check .
    - poetry run mypy .
    - poetry run pytest
  cache:
    paths:
      - .cache/pip
      - .mypy_cache
      - .pytest_cache
      - .ruff_cache
      - .venv
