site_name: CFM Toolbox
site_description: "A plugin-based toolbox for working with cardinality-based feature models."
site_url: https://kit-tva.github.io/cfmtoolbox/
repo_url: https://github.com/KIT-TVA/cfmtoolbox/

theme:
  name: material
  color_mode: auto
  user_color_mode_toggle: true
  features:
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://mkdocstrings.github.io/autorefs/objects.inv
            - https://www.mkdocs.org/objects.inv
            - https://python-markdown.github.io/objects.inv
          paths: [ cfmtoolbox ]
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            filters: [ "!^_" ]
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            parameter_headings: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.details

nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - Plugins:
      - Plugin Overview: plugins/index.md
      - Core Plugins:
          - Conversion: plugins/conversion.md
          - FeatureIDE Import: plugins/featureide-import.md
          - UVL Import: plugins/uvl-import.md
          - UVL Export: plugins/uvl-export.md
          - JSON Import: plugins/json-import.md
          - JSON Export: plugins/json-export.md
          - Big M: plugins/big-m.md
          - Random Sampling: plugins/random-sampling.md
          - One Wise Sampling: plugins/one-wise-sampling.md
          - Debugging: plugins/debugging.md
  - Framework:
      - Architecture: framework/index.md
      - Models: framework/models.md
      - Writing Plugins: framework/writing-plugins.md
      - Contributing: framework/contributing.md
